var sampleTable = '';
sampleTable += '<table border="1">';
sampleTable += '<tbody>';
sampleTable += '<tr>';
sampleTable += '<td/>';
sampleTable += '<td align="center">黄明</td>';
sampleTable += '<td align="center">陈思</td>';
sampleTable += '<td align="center">赵光明</td>';
sampleTable += '<td align="center">陈小红</td>';
sampleTable += '<td align="center">董勇</td>';
sampleTable += '</tr>';
sampleTable += '<tr>';
sampleTable += '<td align="right">黄明</td>';
sampleTable += '<td/>';
sampleTable += '<td/>';
sampleTable += '<td/>';
sampleTable += '<td/>';
sampleTable += '<td/>';
sampleTable += '</tr>';
sampleTable += '<tr>';
sampleTable += '<td align="right">陈思</td>';
sampleTable += '<td align="center"><select><option>完全不认识</option></select></td>';
sampleTable += '<td/>';
sampleTable += '<td/>';
sampleTable += '<td/>';
sampleTable += '<td/>';
sampleTable += '</tr>';
sampleTable += '<tr>';
sampleTable += '<td align="right">赵光明</td>';
sampleTable += '<td align="center"><select><option>不熟悉</option></select></td>';
sampleTable += '<td align="center"><select><option>一般</option></select></td>';
sampleTable += '<td/>';
sampleTable += '<td/>';
sampleTable += '<td/>';
sampleTable += '</tr>';
sampleTable += '<tr>';
sampleTable += '<td align="right">陈小红</td>';
sampleTable += '<td align="center"><select><option>比较熟悉</option></select></td>';
sampleTable += '<td align="center"><select><option>非常熟悉</option></select></td>';
sampleTable += '<td align="center"><select><option>非常熟悉</option></select></td>';
sampleTable += '<td/>';
sampleTable += '<td/>';
sampleTable += '</tr>';
sampleTable += '<tr>';
sampleTable += '<td align="right">董勇</td>';
sampleTable += '<td align="center"><select><option>完全不认识</option></select></td>';
sampleTable += '<td align="center"><select><option>不熟悉</option></select></td>';
sampleTable += '<td align="center"><select><option>不熟悉</option></select></td>';
sampleTable += '<td align="center"><select><option>比较熟悉</option></select></td>';
sampleTable += '<td/>';
sampleTable += '</tr>';
sampleTable += '</tbody>';
sampleTable += '</table>';